```{r}
#| label: load-packages

library(tidyverse)
library(tidymodels)
library(sf)
library(lme4)
library(lmerTest)
library(MuMIn)
```

```{r}
#| label: load-data

city_grouped <- read.csv("data/airbnb_italian_city_grouped.csv") |>
  mutate(across(where(is.character), str_to_lower))
neighbourhood_grouped <- read.csv("data/airbnb_italian_neighbourhood_grouped.csv") |>
  mutate(across(where(is.character), str_to_lower))
city_neighbourhoods <- read.csv("data/airbnb_italy_city_neighbourhoods.csv") |>
  mutate(across(where(is.character), str_to_lower))
city_data <- read.csv("data/airbnb_italy_city.csv") |>
  mutate(across(where(is.character), str_to_lower))
region_data <- read.csv("data/airbnb_italy_region.csv") |>
  mutate(across(where(is.character), str_to_lower))
neighbourhoods_geo <- st_read("data/airbnb_italy_city_neighbourhoods_geojson.geojson") |>
  mutate(across(where(is.character), str_to_lower))
```

```{r}
#| label: city-data-split

firenze_data <- city_data |> filter(place == "firenze")
milano_data <- city_data |> filter(place == "milano")
napoli_data <- city_data |> filter(place == "napoli")
roma_data <- city_data |> filter(place == "roma")
venezia_data <- city_data |> filter(place == "venezia")
```


```{r}
#| label: geo-viz

neighbourhoods_geo <- neighbourhoods_geo |>
  left_join(city_neighbourhoods, by = "neighbourhood") |>
  transmute(neighbourhood = neighbourhood, city = city.y, 
            neighbourhood_group = neighbourhood_group.x, geometry = geometry)

ggplot(neighbourhoods_geo |> filter(city == "firenze")) + 
  geom_sf() +
  theme_bw()

ggplot(neighbourhoods_geo |> filter(city == "milano")) + 
  geom_sf() +
  theme_bw()

ggplot(neighbourhoods_geo |> filter(city == "napoli")) + 
  geom_sf() +
  theme_bw()

ggplot(neighbourhoods_geo |> filter(city == "roma")) + 
  geom_sf() +
  theme_bw()

ggplot(neighbourhoods_geo |> filter(city == "venezia" & !is.na(neighbourhood_group))) + 
  geom_sf() +
  facet_grid(~ neighbourhood_group) +
  theme_bw()

# ggplot(neighbourhoods_geo |> filter(is.na(city))) + 
#   geom_sf() +
#   theme_bw()
```

```{r}
#| label: grouped-data-creation

grouped_neighbourhoods_full <- neighbourhoods_geo |>
  full_join(neighbourhood_grouped, by = c("neighbourhood" = "neighbourhood", "city" = "place")) |>
  group_by(neighbourhood, city, period) |>
  mutate(period_price = mean(price_median)) |>
  ungroup() |>
  group_by(neighbourhood, city) |>
  mutate(prop_period_price = period_price / sum(period_price) * 3)
  
```

```{r}
#| label: grouped-data-viz

ggplot(grouped_neighbourhoods_full |> filter(city == "firenze")) + 
  geom_sf(aes(fill = review_scores_rating_median)) +
  facet_grid(~ period) +
  scale_fill_gradient(low = "lightblue", high = "darkblue") +
  theme_bw()
```

```{r}
#| label: price-model-fit-lm

all_lm <- lm(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + place, data = city_data)
firenze_lm <- lm(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + neighbourhood, data = firenze_data)
milano_lm <- lm(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + neighbourhood, data = milano_data)
napoli_lm <- lm(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + neighbourhood, data = napoli_data)
roma_lm <- lm(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + neighbourhood, data = roma_data)
venezia_lm <- lm(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + neighbourhood, data = venezia_data)

summary(all_lm)
summary(firenze_lm)
summary(milano_lm)
summary(napoli_lm)
summary(roma_lm)
summary(venezia_lm)


```

```{r}
#| label: mixed-effects-models

all_mixed_effects <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | place), data = city_data)
firenze_mixed_effects <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | neighbourhood), data = firenze_data)
milano_mixed_effects <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | neighbourhood), data = milano_data)
napoli_mixed_effects <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | neighbourhood), data = napoli_data)
roma_mixed_effects <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | neighbourhood), data = roma_data)
venezia_mixed_effects <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | neighbourhood), data = venezia_data)

summary(all_mixed_effects)
summary(firenze_mixed_effects)
summary(milano_mixed_effects)
summary(napoli_mixed_effects)
summary(roma_mixed_effects)
summary(venezia_mixed_effects)

new_mixed_effects <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + place + (1 | id), data = city_data)
summary(new_mixed_effects, correlation = TRUE)
vcov(new_mixed_effects)

new_firenze_mixed_effects <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | id), data = firenze_data)
new_milano_mixed_effects <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | id), data = milano_data)
new_napoli_mixed_effects <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | id), data = napoli_data)
new_roma_mixed_effects <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | id), data = roma_data)
new_venezia_mixed_effects <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | id), data = venezia_data)

summary(new_firenze_mixed_effects)
summary(new_milano_mixed_effects)
summary(new_napoli_mixed_effects)
summary(new_roma_mixed_effects)
summary(new_venezia_mixed_effects)
```

```{r}
#| label: relative-vars-creation

city_data <- city_data |>
  group_by(id) |>
  mutate(relative_price = price / mean(price), prop_reviews = number_of_reviews / sum(number_of_reviews), n = n())

city_data <- city_data |>
  group_by(place) |>
  mutate(relative_lat = abs(latitude - mean(latitude)), relative_long = abs(longitude - mean(longitude)))

city_data |>
  group_by(id) |>
  summarize(n = n()) |>
  ggplot(aes(x = n)) +
  geom_bar()

firenze_data <- city_data |> filter(place == "firenze")
milano_data <- city_data |> filter(place == "milano")
napoli_data <- city_data |> filter(place == "napoli")
roma_data <- city_data |> filter(place == "roma")
venezia_data <- city_data |> filter(place == "venezia")

mean_data <- city_data %>%
  group_by(period, place) %>%
  summarize(mean = mean(relative_price))

ggplot(city_data |> filter(n != 1), aes(x = relative_price)) +
  facet_grid(rows = vars(period), cols = vars(place)) +
  geom_histogram()

ggplot(city_data |> filter(n != 1), aes(x = relative_price)) +
  facet_grid(rows = vars(period), cols = vars(place)) +
  geom_density()

ggplot(city_data, aes(x = prop_reviews)) +
  facet_grid(rows = vars(period), cols = vars(place)) +
  geom_histogram()

boxplot(city_data$relative_price)
boxplot(city_data$prop_reviews)

# density(city_data$relative_lat)
```

```{r}
#| label: rel-price-model-fit-lm

all_rel_lm <- lm(relative_price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + place + period*place, 
                 data = city_data)
firenze_rel_lm <- lm(relative_price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period, 
                     data = firenze_data)
milano_rel_lm <- lm(relative_price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + neighbourhood, 
                    data = milano_data)
napoli_rel_lm <- lm(relative_price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + neighbourhood, 
                    data = napoli_data)
roma_rel_lm <- lm(relative_price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + neighbourhood, 
                  data = roma_data)
venezia_rel_lm <- lm(relative_price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + neighbourhood, 
                     data = venezia_data)

summary(all_rel_lm)
summary(firenze_rel_lm)
summary(milano_rel_lm)
summary(napoli_rel_lm)
summary(roma_rel_lm)
summary(venezia_rel_lm)

new_all_rel_lm <- lm(relative_price ~ period + place + period*place, 
                     data = city_data)
new_firenze_rel_lm <- lm(relative_price ~ period, 
                     data = firenze_data)
new_milano_rel_lm <- lm(relative_price ~ period, 
                     data = milano_data)
new_napoli_rel_lm <- lm(relative_price ~ period, 
                     data = napoli_data)
new_roma_rel_lm <- lm(relative_price ~ period, 
                     data = roma_data)
new_venezia_rel_lm <- lm(relative_price ~ period, 
                     data = venezia_data)

summary(new_all_rel_lm)
summary(new_firenze_rel_lm)
summary(new_milano_rel_lm)
summary(new_napoli_rel_lm)
summary(new_roma_rel_lm)
summary(new_venezia_rel_lm)


extra_roma_rel_lm <- lm(relative_price ~ review_scores_rating + host_is_superhost + period, 
                     data = roma_data)
summary(extra_roma_rel_lm)

ggplot(roma_data, aes(x = relative_price)) +
  geom_histogram() +
  facet_grid(rows = vars(period))

ggplot(roma_data, aes(x = relative_price)) +
  geom_boxplot() +
  facet_grid(rows = vars(period))

roma_data |>
  filter(relative_price <= 2) |>
  ggplot(aes(x = relative_price)) +
  geom_boxplot() +
  facet_grid(rows = vars(period))


extra_roma_rel_lm2 <- lm(relative_price ~ period, 
                     data = roma_data |> filter(n >= 3))
summary(extra_roma_rel_lm2)

extra_all_lm <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + relative_lat + 
                        relative_long + place + period*place + (1 | id), data = city_data)
extra_firenze_lm <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + relative_lat + 
                        relative_long + (1 | id), data = firenze_data)
extra_milano_lm <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + relative_lat + 
                        relative_long + (1 | id), data = milano_data)
extra_napoli_lm <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + relative_lat + 
                        relative_long + (1 | id), data = napoli_data)
extra_roma_lm <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + relative_lat + 
                        relative_long + (1 | id), data = roma_data)
extra_venezia_lm <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + relative_lat + 
                        relative_long + (1 | id), data = venezia_data)

summary(extra_all_lm)
summary(extra_firenze_lm)
summary(extra_milano_lm)
summary(extra_napoli_lm)
summary(extra_roma_lm)
summary(extra_venezia_lm)

anova(extra_all_lm)
anova(extra_firenze_lm)
anova(extra_milano_lm)
anova(extra_napoli_lm)
anova(extra_roma_lm)
anova(extra_venezia_lm)

r.squaredGLMM(extra_all_lm)
r.squaredGLMM(extra_firenze_lm)
r.squaredGLMM(extra_milano_lm)
r.squaredGLMM(extra_napoli_lm)
r.squaredGLMM(extra_roma_lm)
r.squaredGLMM(extra_venezia_lm)

plot(fitted(extra_all_lm), resid(extra_all_lm))
qqnorm(resid(extra_all_lm))
plot(fitted(extra_firenze_lm), resid(extra_firenze_lm))
qqnorm(resid(extra_firenze_lm))
plot(fitted(extra_milano_lm), resid(extra_milano_lm))
qqnorm(resid(extra_milano_lm))
plot(fitted(extra_napoli_lm), resid(extra_napoli_lm))
qqnorm(resid(extra_napoli_lm))
plot(fitted(extra_roma_lm), resid(extra_roma_lm))
qqnorm(resid(extra_roma_lm))
plot(fitted(extra_venezia_lm), resid(extra_venezia_lm))
qqnorm(resid(extra_venezia_lm))
```

```{r}
#| label: mixed-effects-models

all_mixed_effects_rel <- lmer(relative_price ~ accommodates + review_scores_rating + room_type + host_is_superhost + (1 + period | place), 
                              data = city_data)
firenze_mixed_effects_rel <- lmer(relative_price ~ accommodates + review_scores_rating + room_type + host_is_superhost + (1 + period | id), 
                                  data = firenze_data)
milano_mixed_effects_rel <- lmer(relative_price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | neighbourhood), 
                                 data = milano_data)
napoli_mixed_effects_rel <- lmer(relative_price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | neighbourhood), 
                                 data = napoli_data)
roma_mixed_effects_rel <- lmer(relative_price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | neighbourhood), 
                               data = roma_data)
venezia_mixed_effects_rel <- lmer(relative_price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | neighbourhood), 
                                  data = venezia_data)

summary(all_mixed_effects_rel)
summary(firenze_mixed_effects_rel)
summary(milano_mixed_effects_rel)
summary(napoli_mixed_effects_rel)
summary(roma_mixed_effects_rel)
summary(venezia_mixed_effects_rel)

# new_mixed_effects <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + place + (1 | id), data = city_data)
# summary(new_mixed_effects, correlation = TRUE)
# vcov(new_mixed_effects)
# 
# new_firenze_mixed_effects <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | id), data = firenze_data)
# new_milano_mixed_effects <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | id), data = milano_data)
# new_napoli_mixed_effects <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | id), data = napoli_data)
# new_roma_mixed_effects <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | id), data = roma_data)
# new_venezia_mixed_effects <- lmer(price ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + (1 | id), data = venezia_data)
# 
# summary(new_firenze_mixed_effects)
# summary(new_milano_mixed_effects)
# summary(new_napoli_mixed_effects)
# summary(new_roma_mixed_effects)
# summary(new_venezia_mixed_effects)
```

```{r}
#| label: reducing-outliers

price_cutoff <- 1000

city_data |>
  filter(price >= price_cutoff) |>
  ggplot(aes(x = place)) +
  geom_bar()

city_data |>
  mutate(high_price = (price >= price_cutoff)) |>
  ggplot(aes(x = place, fill = high_price)) +
  geom_bar()

city_data |> 
  mutate(high_price = (price >= price_cutoff)) |>
  group_by(place) |>
  summarize(count_high = sum(high_price), prop_high = mean(high_price))

city_data_filtered <- city_data |>
  mutate(high_price = (price >= price_cutoff))

firenze_data_filtered <- city_data_filtered |> filter(place == "firenze")
milano_data_filtered <- city_data_filtered |> filter(place == "milano")
napoli_data_filtered <- city_data_filtered |> filter(place == "napoli")
roma_data_filtered <- city_data_filtered |> filter(place == "roma")
venezia_data_filtered <- city_data_filtered |> filter(place == "venezia")
```

```{r}
#| label: model-reduced-outliers

extra_all_lm_filtered <- lmer(log(price) ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + relative_lat + 
                        relative_long + place + period*place + (1 | id), data = city_data_filtered)
extra_firenze_lm_filtered <- lmer(log(price) ~ review_scores_rating + host_is_superhost + period + (1 | id), data = firenze_data)
extra_milano_lm_filtered <- lmer(log(price) ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + relative_lat + 
                        relative_long + (1 | id), data = milano_data)
extra_milano_lm_filtered2 <- lmer(log(price) ~ review_scores_rating + host_is_superhost + period + (1 | id), data = milano_data)
extra_napoli_lm_filtered <- lmer(log(price) ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + relative_lat + 
                        relative_long + (1 | id), data = napoli_data)
extra_roma_lm_filtered <- lmer(log(price) ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + relative_lat + 
                        relative_long + (1 | id), data = roma_data)
extra_venezia_lm_filtered <- lmer(log(price) ~ accommodates + review_scores_rating + room_type + host_is_superhost + period + relative_lat + 
                        relative_long + (1 | id), data = venezia_data)

summary(extra_all_lm_filtered)
summary(extra_firenze_lm_filtered)
summary(extra_milano_lm_filtered)
summary(extra_milano_lm_filtered2)
summary(extra_napoli_lm_filtered)
summary(extra_roma_lm_filtered)
summary(extra_venezia_lm_filtered)

anova(extra_all_lm_filtered)
anova(extra_firenze_lm_filtered)
anova(extra_milano_lm_filtered)
anova(extra_napoli_lm_filtered)
anova(extra_roma_lm_filtered)
anova(extra_venezia_lm_filtered)

r.squaredGLMM(extra_all_lm_filtered)
r.squaredGLMM(extra_firenze_lm_filtered)
r.squaredGLMM(extra_milano_lm_filtered)
r.squaredGLMM(extra_milano_lm_filtered2)
r.squaredGLMM(extra_napoli_lm_filtered)
r.squaredGLMM(extra_roma_lm_filtered)
r.squaredGLMM(extra_venezia_lm_filtered)

plot(fitted(extra_all_lm_filtered), resid(extra_all_lm_filtered))
qqnorm(resid(extra_all_lm_filtered))
qqline(resid(extra_all_lm_filtered))
plot(fitted(extra_firenze_lm_filtered), resid(extra_firenze_lm_filtered))
qqnorm(resid(extra_firenze_lm_filtered))
qqline(resid(extra_firenze_lm_filtered))
plot(fitted(extra_milano_lm_filtered), resid(extra_milano_lm_filtered))
qqnorm(resid(extra_milano_lm_filtered))
qqline(resid(extra_milano_lm_filtered))
plot(fitted(extra_napoli_lm_filtered), resid(extra_napoli_lm_filtered))
qqnorm(resid(extra_napoli_lm_filtered))
qqline(resid(extra_napoli_lm_filtered))
plot(fitted(extra_roma_lm_filtered), resid(extra_roma_lm_filtered))
qqnorm(resid(extra_roma_lm_filtered))
qqline(resid(extra_roma_lm_filtered))
plot(fitted(extra_venezia_lm_filtered), resid(extra_venezia_lm_filtered))
qqnorm(resid(extra_venezia_lm_filtered))
qqline(resid(extra_venezia_lm_filtered))

ggplot(firenze_data, aes(x = log(price))) +
  geom_density()
```

